import Player from "../src/player";
import Gameboard from "../src/gameboard";
import Ship from "../src/ship";

/* global test, expect, beforeEach */

const myShips = [Ship("Carrier",5),Ship("Battleship",4),Ship("Destroyer",3),Ship("Submarine",3),Ship("Patrol Boat",2)]
let myPlayer;

beforeEach(() => {
    myPlayer = Player("AI",myShips);
});

/* test("Print a board generated by an AI player", () => {
    const myBoard = myPlayer.getGameBoard()

    expect()
}) */