import Player from "../src/player";
import Ship from "../src/ship";

/* global test, expect, beforeEach */

const myShips = [Ship("Carrier",5),Ship("Battleship",4),Ship("Destroyer",3),Ship("Submarine",3),Ship("Patrol Boat",2)]
const player1 = Player("AI",myShips)
const player2 = Player("AI",myShips)
const player3 = Player("Human",myShips)

beforeEach(() => {
    player1.placeShips()
    player2.placeShips()
})

test("Create 2 boards generated by AI players", () => {
    // Player 1 gameboard has 5 ships
    expect(player1.getGameBoard().getShips().length).toBe(5)
    // Player 2 gameboard has 5 ships
    expect(player2.getGameBoard().getShips().length).toBe(5)
})